GET  http://localhost:5000/products

###

GET  http://localhost:5000/products/1

###

POST http://localhost:5000/products
Content-Type: application/json

{
    "name": "Kopi Vietnam Drip",
    "code": "K-01",
    "price": 7000
}

###

PUT http://localhost:5000/products/3
Content-Type: application/json

{
    "name": "Kecap Manis banget Up",
    "price": 9000
}

###

DELETE http://localhost:5000/products/28